/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PreDealsRouteImport } from './routes/pre-deals'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HardeningNotesRouteImport } from './routes/hardening-notes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PreDealsRoute = PreDealsRouteImport.update({
  id: '/pre-deals',
  path: '/pre-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HardeningNotesRoute = HardeningNotesRouteImport.update({
  id: '/hardening-notes',
  path: '/hardening-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HardeningNotesRoute: typeof HardeningNotesRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PreDealsRoute: typeof PreDealsRoute
  ProductsRoute: typeof ProductsRoute
  SanctionsRoute: typeof SanctionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-deals': {
      id: '/pre-deals'
      path: '/pre-deals'
      fullPath: '/pre-deals'
      preLoaderRoute: typeof PreDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardening-notes': {
      id: '/hardening-notes'
      path: '/hardening-notes'
      fullPath: '/hardening-notes'
      preLoaderRoute: typeof HardeningNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HardeningNotesRoute: HardeningNotesRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PreDealsRoute: PreDealsRoute,
  ProductsRoute: ProductsRoute,
  SanctionsRoute: SanctionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
