/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeFinanceRouteImport } from './routes/trade-finance'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SanctionsRouteImport } from './routes/sanctions'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PreDealsRouteImport } from './routes/pre-deals'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MlAnalyticsRouteImport } from './routes/ml-analytics'
import { Route as MicroservicesSpecRouteImport } from './routes/microservices-spec'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as HardeningNotesRouteImport } from './routes/hardening-notes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'

const TradeFinanceRoute = TradeFinanceRouteImport.update({
  id: '/trade-finance',
  path: '/trade-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SanctionsRoute = SanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PreDealsRoute = PreDealsRouteImport.update({
  id: '/pre-deals',
  path: '/pre-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MlAnalyticsRoute = MlAnalyticsRouteImport.update({
  id: '/ml-analytics',
  path: '/ml-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroservicesSpecRoute = MicroservicesSpecRouteImport.update({
  id: '/microservices-spec',
  path: '/microservices-spec',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const HardeningNotesRoute = HardeningNotesRouteImport.update({
  id: '/hardening-notes',
  path: '/hardening-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/microservices-spec': typeof MicroservicesSpecRoute
  '/ml-analytics': typeof MlAnalyticsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
  '/shipments': typeof ShipmentsRoute
  '/trade-finance': typeof TradeFinanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/microservices-spec': typeof MicroservicesSpecRoute
  '/ml-analytics': typeof MlAnalyticsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
  '/shipments': typeof ShipmentsRoute
  '/trade-finance': typeof TradeFinanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/hardening-notes': typeof HardeningNotesRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/microservices-spec': typeof MicroservicesSpecRoute
  '/ml-analytics': typeof MlAnalyticsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/pre-deals': typeof PreDealsRoute
  '/products': typeof ProductsRoute
  '/sanctions': typeof SanctionsRoute
  '/shipments': typeof ShipmentsRoute
  '/trade-finance': typeof TradeFinanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/microservices-spec'
    | '/ml-analytics'
    | '/notifications'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
    | '/shipments'
    | '/trade-finance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/microservices-spec'
    | '/ml-analytics'
    | '/notifications'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
    | '/shipments'
    | '/trade-finance'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/hardening-notes'
    | '/kyc'
    | '/login'
    | '/microservices-spec'
    | '/ml-analytics'
    | '/notifications'
    | '/orders'
    | '/pre-deals'
    | '/products'
    | '/sanctions'
    | '/shipments'
    | '/trade-finance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  HardeningNotesRoute: typeof HardeningNotesRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  MicroservicesSpecRoute: typeof MicroservicesSpecRoute
  MlAnalyticsRoute: typeof MlAnalyticsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PreDealsRoute: typeof PreDealsRoute
  ProductsRoute: typeof ProductsRoute
  SanctionsRoute: typeof SanctionsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  TradeFinanceRoute: typeof TradeFinanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-finance': {
      id: '/trade-finance'
      path: '/trade-finance'
      fullPath: '/trade-finance'
      preLoaderRoute: typeof TradeFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanctions': {
      id: '/sanctions'
      path: '/sanctions'
      fullPath: '/sanctions'
      preLoaderRoute: typeof SanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-deals': {
      id: '/pre-deals'
      path: '/pre-deals'
      fullPath: '/pre-deals'
      preLoaderRoute: typeof PreDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-analytics': {
      id: '/ml-analytics'
      path: '/ml-analytics'
      fullPath: '/ml-analytics'
      preLoaderRoute: typeof MlAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microservices-spec': {
      id: '/microservices-spec'
      path: '/microservices-spec'
      fullPath: '/microservices-spec'
      preLoaderRoute: typeof MicroservicesSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardening-notes': {
      id: '/hardening-notes'
      path: '/hardening-notes'
      fullPath: '/hardening-notes'
      preLoaderRoute: typeof HardeningNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  HardeningNotesRoute: HardeningNotesRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  MicroservicesSpecRoute: MicroservicesSpecRoute,
  MlAnalyticsRoute: MlAnalyticsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PreDealsRoute: PreDealsRoute,
  ProductsRoute: ProductsRoute,
  SanctionsRoute: SanctionsRoute,
  ShipmentsRoute: ShipmentsRoute,
  TradeFinanceRoute: TradeFinanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
